### ISSUE TITLE
Feature suggestion: option to include non-required properties in UI but exclude when empty from resulting JSON

### ISSUE THREAD

**Issue by tupelo-schneck** [jdorn/json-editor#220]
We find the UI for including or excluding non-required properties to be a bit clunky and non-intuitive.  We'd prefer to just have all the non-required fields in the UI available to be edited, but have them get excluded from the constructed JSON unless data is entered.

Obviously, we lose the ability to distinguish between "property undefined" and "property value is empty string".  We don't mind that.

Here's a bit of code we're using that, in our case, has the desired effect.  

```
var oldObjectEditor = JSONEditor.defaults.editors.object;
JSONEditor.defaults.editors.object = oldObjectEditor.extend({
    isRequired: function (editor) {
        // treat everything as required so that all fields show up in the UI
        return true;
    },
    refreshValue: function () {
        this._super();
        var required = this.schema.required;
        var hasRequired = $.isArray(required);
        for (var i in this.editors) {
            if (!this.editors.hasOwnProperty(i)) continue;
            if (hasRequired && required.indexOf(i) > -1) continue;
            var val = this.value[i];
            if (!val) delete this.value[i];
            else if ($.isEmptyObject(val)) delete this.value[i];
            else if ($.isArray(val) && val.length == 0) delete this.value[i];
        }
    } 
});
JSONEditor.defaults.editors.object.options = oldObjectEditor.options;
```

We think this might be useful to other users and so propose that it be available as an editor option.

**Comment by lykahb** [comment]
Thank you for this feature, it is very helpful. But I found a couple of corner cases. The option remove_empty_properties is not aware of the schema. It will be nice if it preserves the keys with empty values for the required fields.

For example, if the user enters nothing for following schema, the JSON will be

    {
        "header": ""
    }

because "header" is required and "innerObject" is not and all of its fields are empty, so it can be treated as an empty field itself. At the same time, if a user changes one field of the inner object, both fields appear

    {
        "header": "",
        "innerObject": {
            "field1": "user input",
            "field2": ""
        }
    }

which will make the JSON conforming to the schema with minimum of the user interaction

    {
        "type": "object",
        "properties": {
            "required": [
                "header"
            ],
            "header": {
                "type": "string"
            },
            "innerObject": {
                "type": "object",
                "required": [
                    "field1",
                    "field2"
                ],
                "properties": [
                    "field1": {
                        "type": "string"
                    },
                    "field2": {
                        "type": "string"
                    }
                ]
            }
        }
    }
