### ISSUE TITLE
Select2 setting value, wrong ui display

### ISSUE THREAD

**Issue by DJWassink** [jdorn/json-editor#225]
When you use Select2 and set the data, the displayed data is the first enum item not the value passed to the editor.
However if you click on the dropdown menu, the correct item is highlighted (also visible in the json editor and gets posted when you submit the form).

I tried adding the following code below line 121 (https://github.com/jdorn/json-editor/blob/master/src/editors/select.js#L121)

```
window.jQuery(this.input).select2('val', this.value);
```

which didn't work cause the this.value = the first enum option (this is double weird cause if I log 'this' and I look in the console then this.value = correct but when I console.log(this.value); it shows the first enum option).

Anyway if I use the above code and manually fill in the this.value with a string representing the value of a enum it will correctly select that.

In the attached image you can clearly see that it has project selected but the hmiScreenElement is setted by the editor.set method.
![select](https://cloud.githubusercontent.com/assets/1822404/3911241/74d3ed9c-231f-11e4-954e-f2027ae54f54.png)

**Comment by joseaio** [comment]
select2 (multiselect) not works for dinamic enums (watch+enumSource+value)

              "attributes":{
                  "type": "array",
                  "uniqueItems": true,
                  "format": "table",
                  "items": {
                     "type":"string",
                     "watch": { "fields2": "properties" },
                     "enumSource":["none",{"source": "fields2","value": "{{item.name}}"}]
                  }

**Comment by joshco** [comment]
I've been struggling to make multiselect work with selectize using a comma delimited string as the value of a string property for tags.  The scenario led me to manually instantiate selectize on a string property and populate the options via javascript rather than json schema.

> I want the value to be tags: "volunteer,superhero,parent" rather than be an array

The big sticking point is that json-editor isn't catching the change events, as mentioned here previously.  Selectize was updating the input field, and json-editor wasn't noticing it.  What was _really_ strange is that manually doing a editor.setValue() did not work because json-editor seems to know at some level that the value is already set, so it wouldnt update it, but still reports an empty value when doing getValue(). 

What I needed to do was first setValue with a fake string, and then reset it to the value that selectize had already written to the input field.  

Here's my javascript event handler.  I'm finding the form input by the name (expecting it to have tags in it), then using that to find the parent div with the data schema path value (root.includes.0.tags) and then using that to select the json-editor child editor, and then doing the double setValue() on it.

> the selectize options is constructed with some ruby interpolation magic you can ignore

````
  var json_editor_handler = function(event) {

     // this function is called when the page loads, or json-editor changes
    console.log("jseditor change");

     // manually selectize
    $('input.form-control[name*="tags"]').selectize({
      delimiter: ',',
      persist: false,
      options: #{ @customer_current.tags_existing.map{|o| {value: o, text: o}}.to_json},
      create: false

    });

    // listen to change events on the input field from selectize
    $('input.form-control[name*="tags"]').on('change', function() {
      var new_value=$(this).val();

      // find the parent div with the schema path
      var schema_path=$(this).parents('div[data-schemapath*="tags"]').attr('data-schemapath');
        console.log("selectize change ",new_value,schema_path);

       // find the right json-editor child editor, then ram the right value in with excessive force
        jseditor.getEditor(schema_path).setValue("DEADBEEF");
        jseditor.getEditor(schema_path).setValue(new_value);
      })
  };

// set up event handlers
  jseditor.on("change", json_editor_handler);
  $(document).on("page:change", json_editor_handler);

````
__Happy New Year__
