### ISSUE TITLE
Multiple types for the same property 

### ISSUE THREAD

**Issue by mihaivinaga** [jdorn/json-editor#505]
I find myself in need of having a property, ex: "Title" to be either a string or an object, I have done this by removing the type all togheter but now the user can set it to be a number for example. 

Is there anyway of saying that this property can be only string or objectt, something like this: "title":{"string|object"}?

String: {"title": "Install our multi themes Keyboard App",}
Objectt: {"title": {
        "type": "tme.string",
        "values": {
          "def": "Decoration Time! Wallpapers available to match %name%!",
          "es": "Tiempo Decoración! Fondos de pantalla disponibles para que coincida %name%!",
          "pt": "Decoração Time! Wallpapers disponíveis para combinar %name%!"
        }
      }}

Thanks

**Comment by mihaivinaga** [comment]
Found the answer, @bogdan00 found the the answer:

"title":{
  "type": ["string","object"]
}

This will display only the string and object type for the Title property

**Comment by mshenfield** [comment]
@mihaivinaga Just wanted to add that the json-schema attribute [`"oneOf"`](http://json-schema.org/latest/json-schema-validation.html#anchor89) would also work. The advantage is that you can define a full schema for the object, instead of making the user add custom properties.  Below is an example where the `"Title"` property can be either a string, or an object with a `"Header"`, and `"SubHeader"` property.

```
"Title": {
  "oneOf": [
    {
      "type": "string",
      "description": "Simple string Title"
    },
    {
      "type": "object",
      "description": "Complex Title object with Header and SubHeader",
      "properties": {
        "Header": {
          "type": "string"
        },
        "SubHeader": {
          "type": "string"
        }
      }
    }
  ]
}
```
